### ISSUE TITLE
Add defined.net

### ISSUE THREAD

**Issue by jasikpark** [delucis/hyperdrive-speedometer#4]
We have a landing page at defined.net that is built with Astro, but is closed source - could it be added here?

I see that currently this lists only astro showcase sites, right?

**Comment by jasikpark** [comment]
https://github.com/withastro/astro.build/issues/272 aha!

**Comment by jasikpark** [comment]
wait that might not work anymore..

**Comment by delucis** [comment]
Still works! Tony or I periodically go through and grab those issues and add them to the showcase.
